# Generated by Django 5.0.7 on 2024-08-16 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registroapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Usuario', models.CharField(max_length=40)),
                ('Contraseña', models.CharField(max_length=40)),
                ('Comision', models.CharField(max_length=40)),
            ],
        ),
    ]
